FROM php:8.3-fpm

WORKDIR /var/www

#RUN apt-get update \
#&& apt-get install -y curl zip libzip-dev libicu-dev libpng-dev \
#&& docker-php-ext-install zip mysqli pdo pdo_mysql intl gd bcmath gettext \
#&& docker-php-ext-enable pdo_mysql intl gd bcmath gettext

#RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
#RUN composer install
